# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('surname', models.CharField(blank=True, max_length=120)),
                ('year_of_birth', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('year_of_death', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('biography', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Автори',
                'ordering': ['name', 'surname'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('year_of_published', models.DecimalField(blank=True, decimal_places=0, max_digits=4)),
                ('count', models.DecimalField(decimal_places=0, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Author')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category'),
        ),
    ]
