# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20171029_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='books', verbose_name='Зображення книги'),
        ),
    ]
