# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 15:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20171219_2246'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderedItem',
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-date_of_creation',), 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paid',
            new_name='is_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created',
        ),
        migrations.AddField(
            model_name='order',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 12, 20, 15, 32, 35, 874423, tzinfo=utc), verbose_name='Date of creation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Is confirmed'),
        ),
    ]
